### ISSUE TITLE
Bug: setup fails to create views

### ISSUE THREAD

**Issue by zgjs** [466-mysequel/fitnesstracker#77]
When I run `setup.sh` it fails on the creating views step, due to this code:
https://github.com/466-mysequel/fitnesstracker/blob/7435b803d43ede94c545865564d5ea35b17d323a/sql/views.sql#L88-L93
Line 89 is causing `setup.sh` to fail because it is missing a matching `DROP VIEW` statement in the `tables.sql` file.

**Comment by zgjs** [comment]
This was added in commit https://github.com/466-mysequel/fitnesstracker/commit/e46c754669cdf11830f50ebc1915fa90617748b8 for issue #59 but it does not resolve the issue. Can this commit be reverted?

**Comment by J-Erwin** [comment]
Sure, if that is the way you want to do it
